---
tags: [spring-cloud, eureka]
projects: [spring-cloud, spring-cloud-netflix]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-service-registration-and-discovery

本指南将带你一步一步建立和消费 Netflix Eureka的服务注册中心.

== 你将构建什么

你将建立 https://github.com/spring-cloud/spring-cloud-netflix[Netflix Eureka 服务注册] 然后构建一个客户端，既注册自己，又使用注册中心来解析自己的主机。服务注册中心是有用的,因为它使客户端负载均衡,消费者不需要DNS就解耦了服务提供者。

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[reveal-gradle]]
[.reveal-gradle]
== Build with Gradle

[[scratch]]
[.use-gradle]
== Build with Gradle

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_both_builds.adoc[]

`eureka-service/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/eureka-service/build.gradle[]
----

`eureka-client/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/eureka-client/build.gradle[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]

[[reveal-maven]]
[.reveal-maven]
== Build with Maven

[[use-maven]]
[.use-maven]
== Build with Maven

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro_maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]

`eureka-service/pom.xml`
[source,xml]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/eureka-service/pom.xml[]
----

`eureka-client/pom.xml`
[source,xml]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/eureka-client/pom.xml[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-maven-plugin.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]


[[initial]]
== 建立一个Eureka服务注册
您首先需要一个Eureka服务注册中心。你可以用Spring Cloud的 `@EnableEurekaServer` 建立注册中心，它可以和其他应用程序交流。这是一个常规的Spring Boot应用，添加一个注释就 _enable_ 了服务注册中心。

`eureka-service/src/main/java/hello/EurekaServiceApplication.java`
[source,java]
----
include::complete/eureka-service/src/main/java/hello/EurekaServiceApplication.java[]
----

当注册中心启动时它会抱怨说：，用一个堆栈，没有注册中心可以连接的副本节点。在生产环境中，您将需要多个注册中心实例。然而，为了简单，它可以禁用相关日志。

默认情况下，注册中心将 _也_ 试图登记本身，所以你也需要禁用这个功能。

在本地使用此注册中心时，将其放在单独的端口上是一个很好的约定。

将一些属性添加到您的 `eureka-service/src/main/resources/application.properties` ，以处理所有这些需求。

`eureka-service/src/main/resources/application.properties`
[source,properties]
----
include::complete/eureka-service/src/main/resources/application.properties[]
----


== 与注册中心联系

现在我们已经建立了一个服务注册中心，让我们建立一个客户端自己注册到注册中心，然后使用 Spring Cloud `DiscoveryClient` 抽象类去询问注册中心它自己的主机和端口。 `@EnableDiscoveryClient` 激活 Netflix Eureka `DiscoveryClient` 实现类。还有其他服务注册中心的实现：如https://www.consul.io/[Hashicorp's Consul] or https://zookeeper.apache.org/[Apache Zookeeper]。

`eureka-client/src/main/java/hello/EurekaClientApplication.java`
[source,java]
----
include::complete/eureka-client/src/main/java/hello/EurekaClientApplication.java[]
----

无论你选择的什么实现，你很快就会看到一个 `eureka-client`被注册了，使用了你在 `spring.application.name` 属性指定的名字，。此属性在 Spring Cloud 中经常使用，通常在服务配置的最早阶段。这个属性是用来服务引导，因此按照惯例放在 `eureka-client/src/main/resources/bootstrap.properties` 文件中，这个文件会比 `src/main/resources/application.properties`  _先_ 读取。

`eureka-client/src/main/resources/bootstrap.properties`
[source,properties]
----
include::complete/eureka-client/src/main/resources/bootstrap.properties[]
----

The `eureka-client` defines a Spring MVC REST endpoint, `ServiceInstanceRestController`, that returns an enumeration of all the `ServiceInstance` instances registered in the registry at  `http://localhost:8080/service-instances/a-bootiful-client`. Consult the https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service]  guide to learn more about building REST services with Spring MVC and Spring Boot.

== 测试应用

Test the end-to-end result by starting the `eureka-service` first and then, once loaded, starting the `eureka-client`. The `eureka-client` will take about a minute to register itself in the registry and to refresh its own list of registered instances from the registry. All of these thresholds are configurable. Visit the `eureka-client` in the browser, `http://localhost:8080/service-instances/a-bootiful-client`. There, you should see the `ServiceInstance` for the `eureka-client` reflected in the response.


== 总结
Congratulations! You've just used Spring to stand up a Netflix Eureka service registry and to use that registry in a client application.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
